name: Cloudflare Tunnel aarch64 (64 bit, ARM, 2022.11.0)
version: 2022.11.0
slug: cloudflared_tunnel_aarch64
description: Argo tunnel provided for free by Cloudflare
arch:
  - aarch64
startup: application
boot: auto
init: false
options:
  localUrl: http://homeassistant.local.hass.io:8123
  tunnelName: homeassistant
  hostname: homeassistant.example.com
schema:
  localUrl: url
  tunnelName: str
  hostname: str
